# Generated by Django 3.2 on 2022-12-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('stream', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('company', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('linkedin', models.URLField(unique=True)),
                ('twitter', models.URLField(null=True, unique=True)),
                ('github', models.URLField(null=True, unique=True)),
                ('gender', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('profile_photo', models.ImageField(blank=True, upload_to='profileimg/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
