# Generated by Django 3.2 on 2022-12-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=500, null=True)),
                ('industry', models.CharField(max_length=200)),
                ('employees', models.CharField(max_length=200)),
                ('employee_growth', models.CharField(max_length=200)),
                ('revenue', models.CharField(max_length=200)),
                ('technologies', models.CharField(max_length=200)),
                ('linkedin', models.URLField(unique=True)),
                ('twitter', models.URLField(null=True, unique=True)),
                ('profile_photo', models.ImageField(blank=True, upload_to='companyimg/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
